set(SERENITY_CPPS
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/BoughtonPulayAlgorithm.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/DOIBasedSelector.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PNOConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/TNOConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/brokenSymmetry/BrokenSymmetry.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/brokenSymmetry/CorrespondingOrbitals.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/directOrbitalSelection/DirectOrbitalSelection.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/ELFCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/SEDD.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/MultipoleMomentCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/NumericalDipoleMomentCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/EdmistonRuedenbergLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/FosterBoysLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/IBOLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/NonOrthogonalLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/OrbitalAligner.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/PipekMezeyLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/SPADEAlgorithm.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/BeckePopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/CHELPGPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/CM5PopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/HirshfeldPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/IAOPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/LoewdinPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/MullikenPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/ABShellPairCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisController.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisControllerFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisController.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisExtension.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionMapper.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionProvider.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CartesianToSphericalTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CombinedShellPair.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CustomBasisController.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/Shell.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/SphericalHarmonicsRotations.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/Transformation.cpp
  ${PROJECT_SOURCE_DIR}/src/data/ElectronicStructure.cpp
  ${PROJECT_SOURCE_DIR}/src/data/ExternalChargeController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPair.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPairSet.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTriple.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTripleSet.cpp
  ${PROJECT_SOURCE_DIR}/src/data/PAOController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/SingleSubstitution.cpp
  ${PROJECT_SOURCE_DIR}/src/data/SparseMapsController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridControllerFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombIntegralsOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombPotentialOnGridCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityAdder.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityMatrixDensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DifferentialOverlapIntegralCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ElectrostaticPotentialOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ExternalDensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/MOCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/MatrixOperatorToGridTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ScalarOperatorToMatrixAdder.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/SupersystemDensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/MatrixInBasis.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/SPMatrix.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/Functional.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionCorrectionCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionData.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/FunctionalLibrary.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/LibXC.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/XCFun.cpp
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentController.cpp
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentPrinter.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Atom.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomType.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomTypeFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/DelleySurfaceConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Ellipse.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GEPOLSurfaceConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryAdderFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryFileReader.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Line.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurface.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceController.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Plane.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Point.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Sphere.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Triangle.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/XyzFileToGeometryConverter.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/efields/EFieldPlates.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/CoreCoreRepulsionDerivative.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalGeomGradCalc.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalHessianCalc.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/TDDFTGradientCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGridControllerFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GaussLegendre.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GridController.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/HilbertRTreeSorting.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGridFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/GridFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/sphere_lebedev_rule.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/CDIntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/CDStorageController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/IntegralCachingController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/MO3CenterIntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/OneElectronIntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/OneElectronIntegralDerivativeCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/RIIntegralDerivativeCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/RI_J_IntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/CholeskyDecomposer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/SimpleCholeskyDecomposer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/TwoElecFourCenterIntDecomposer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/TwoElecTwoCenterIntDecomposer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/TwoElecThreeCenterCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoExchangeIntegralTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoHalfTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libecpint.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint.cpp
  ${PROJECT_SOURCE_DIR}/src/io/CubeFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/DataOnGridWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/ExternalChargeReader.cpp
  ${PROJECT_SOURCE_DIR}/src/io/FCIDumpFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/Filesystem.cpp
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutput.cpp
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutputStream.cpp
  ${PROJECT_SOURCE_DIR}/src/io/GeneralGridFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/IOOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/io/MolecularSurfaceGridFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/PlaneFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/math/diis/ADIIS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/diis/DIIS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/JacobiRotation.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/PadeApproximation.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/BFGS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/LBFGS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/NewtonRaphson.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SQNM.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SteepestDescent.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/Bofill.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/QST.cpp
  ${PROJECT_SOURCE_DIR}/src/memory/MemoryManager.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/BasisSetTruncationAlgorithms.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/FaTConvergenceAccelerator.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/SystemSplittingTools.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/Timing.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/VectorOnDiskStorageController.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/VirtualOrbitalSelectionAlgorithms.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/WarningTracker.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD_T.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_T0.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/ET/FDEDiabController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/ET/FDEETCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/ET/FDEETController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DeltaSpinSquared.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DipoleIntegrals.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ExcitationSpectrum.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFAnalysis.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFPopulationAnalysis.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/NROCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/NTOCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ResponseProperties.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Kernel/Kernel.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/LRSCFController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/ADC2DensityTransition.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/ADC2Sigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Amplitudes.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Controller.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2DensityExcitedState.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2DensityGroundstate.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2DensityPerturbed.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2DensityTransition.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2DressedIntegrals.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2FContractions.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Groundstate.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2HelperFunctions.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2IntDirectFunctions.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2MultiplierExcitedState.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2MultiplierGroundState.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2MultiplierTransition.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Normalization.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Perturbation.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Residual.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Sigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/CoulombSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/EOSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/ExchangeSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/FockSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/GrimmeSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/HyperkernelSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/KernelSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/RI/MRICoulombSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/RI/RICoulombSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/RI/RIExchangeSigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/Sigmavector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/Besley.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/CouplingConstruction.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/EigenvalueSolver.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/LRSCFRestart.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/LRSCFSetup.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/NonlinearEigenvalueSolver.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/NonlinearResponseSolver.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/RIIntegrals.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseLambda.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseSolver.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/SimplifiedTDDFT.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/CouplingOrbitalSet.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/DomainOverlapMatrixController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/KLOrbitalSet.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalAOSigmaVectorWrapper.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalCorrelationController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/OrbitalPairDIISWrapper.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/GW_Analytic.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/GW_AnalyticContinuation.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/GW_ContourDeformation.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/MBPT.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/DipoleApproximationToPairEnergies.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LTMP2.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2InteractionCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/MP2.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/OrbitalPairSelector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/RIMP2.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundle.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundleFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoreHamiltonian.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoulombInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABERIPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABEffectiveCorePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABFuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABLRExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABNAddFuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/BUReconstructionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CDHFPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ChargeElectronInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ECPInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ERIPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/EffectiveCorePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangeInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/FuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HCorePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HFPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HoffmannProjectionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HuzinagaProjectionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/IncrementalFockMatrix.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LRXPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftHybridPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LoewdinFDEProjectionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NAddFuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NEInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/OptEffPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/PCMPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/RICoulombPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/RIExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/SAOPPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/TDReconstructionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/ALMOPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/DFTPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/EDAPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/ESIPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentialBundleFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/HFPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/PBEPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/ConvergenceController.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/DeltaScf.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/ROHF.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/SCFAnalysis.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/Scf.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/damper/Damper.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/AtomicDensityGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/DensityInitialGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/ExtendedHueckel.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/HCoreGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/SuperpositionOfAtomicPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/BasisOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/CorrelatedMethodsOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/DFTOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/ElectronicStructureOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/GeometryOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/GridOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/LRSCFOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/LocalizationOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/MBPTOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/MiscOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/OrthogonalizationOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/PCMOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/SCFOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Settings.cpp
  ${PROJECT_SOURCE_DIR}/src/solvation/ContinuumModel.cpp
  ${PROJECT_SOURCE_DIR}/src/solvation/Solvents.cpp
  ${PROJECT_SOURCE_DIR}/src/system/SystemController.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ActiveSpaceSelectionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/BasisSetTruncationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/BrokenSymmetryTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DFTEmbeddedLocalCorrelationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DOSCCTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DummyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EDATask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronTransferTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronicStructureCopyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EvaluateEnergyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportCavityTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportGridTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FCIDumpFileWriterTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FXDTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FiniteFieldTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GWTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeneralizedDOSTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/HessianTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ImportCavityTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalCorrelationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/OrbitalsIOTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/OrthogonalizationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PCMInteractionEnergyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PopAnalysisTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/QuasiRestrictedOrbitalsTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TSTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/Task.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TopDownStaticEmbeddingTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/VirtualOrbitalSpaceSelectionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/WavefunctionEmbeddingTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/WriteIntegralsTask.cpp
)

set(SERENITY_HEADERS
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/BoughtonPulayAlgorithm.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/DOIBasedSelector.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PAOSelector.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PNOConstructor.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/TNOConstructor.h
  ${PROJECT_SOURCE_DIR}/src/analysis/brokenSymmetry/BrokenSymmetry.h
  ${PROJECT_SOURCE_DIR}/src/analysis/brokenSymmetry/CorrespondingOrbitals.h
  ${PROJECT_SOURCE_DIR}/src/analysis/directOrbitalSelection/DirectOrbitalSelection.h
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/ELFCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/SEDD.h
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/MultipoleMomentCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/NumericalDipoleMomentCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/EdmistonRuedenbergLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/FosterBoysLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/IBOLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/Localization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/NonOrthogonalLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/OrbitalAligner.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/PipekMezeyLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/SPADEAlgorithm.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/BeckePopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/CHELPGPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/CM5PopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/HirshfeldPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/IAOPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/LoewdinPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/MullikenPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/basis/ABShellPairCalculator.h
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisController.h
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/basis/Basis.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisController.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisExtension.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionMapper.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionProvider.h
  ${PROJECT_SOURCE_DIR}/src/basis/CartesianToSphericalTransformer.h
  ${PROJECT_SOURCE_DIR}/src/basis/CombinedShellPair.h
  ${PROJECT_SOURCE_DIR}/src/basis/CustomBasisController.h
  ${PROJECT_SOURCE_DIR}/src/basis/Shell.h
  ${PROJECT_SOURCE_DIR}/src/basis/SphericalHarmonicsRotations.h
  ${PROJECT_SOURCE_DIR}/src/basis/Transformation.h
  ${PROJECT_SOURCE_DIR}/src/data/DoublySpinPolarizedData.h
  ${PROJECT_SOURCE_DIR}/src/data/ElectronicStructure.h
  ${PROJECT_SOURCE_DIR}/src/data/ExternalChargeController.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalController.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPair.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPairSet.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTriple.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTripleSet.h
  ${PROJECT_SOURCE_DIR}/src/data/PAOController.h
  ${PROJECT_SOURCE_DIR}/src/data/SingleSubstitution.h
  ${PROJECT_SOURCE_DIR}/src/data/SparseMapsController.h
  ${PROJECT_SOURCE_DIR}/src/data/SpinPolarizedData.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombIntegralsOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombPotentialOnGridCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/CustomDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityAdder.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityMatrixDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGrid.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridFactory.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DifferentialOverlapIntegralCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/ElectrostaticPotentialOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/ExternalDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridData.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridPotential.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/MOCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/MatrixOperatorToGridTransformer.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/ScalarOperatorToMatrixAdder.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/SupersystemDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/CoefficientMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/FockMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/MatrixInBasis.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/SPMatrix.h
  ${PROJECT_SOURCE_DIR}/src/dft/Functional.h
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionCorrectionCalculator.h
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionData.h
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionRawData.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/FunctionalLibrary.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/LibXC.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/PartialDerivatives.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/XCFun.h
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentController.h
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentPrinter.h
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyContributions.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Atom.h
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomType.h
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomTypeFactory.h
  ${PROJECT_SOURCE_DIR}/src/geometry/DelleySurfaceConstructor.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Ellipse.h
  ${PROJECT_SOURCE_DIR}/src/geometry/GEPOLSurfaceConstructor.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry.h
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryAdderFactory.h
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryFileReader.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Line.h
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurface.h
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceController.h
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceFactory.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Plane.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Point.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Sphere.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Triangle.h
  ${PROJECT_SOURCE_DIR}/src/geometry/XyzFileToGeometryConverter.h
  ${PROJECT_SOURCE_DIR}/src/geometry/efields/EFieldPlates.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/CoreCoreRepulsionDerivative.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/GeometryGradientCalculator.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/HessianCalculator.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalGeomGradCalc.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalHessianCalc.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/TDDFTGradientCalculator.h
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGrid.h
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGridController.h
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGridControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/grid/GaussLegendre.h
  ${PROJECT_SOURCE_DIR}/src/grid/Grid.h
  ${PROJECT_SOURCE_DIR}/src/grid/GridController.h
  ${PROJECT_SOURCE_DIR}/src/grid/HilbertRTreeSorting.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGrid.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGridFactory.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/GridFactory.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/sphere_lebedev_rule.h
  ${PROJECT_SOURCE_DIR}/src/input/Input.h
  ${PROJECT_SOURCE_DIR}/src/integrals/CDIntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/CDStorageController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/IntegralCachingController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/MO3CenterIntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/Normalization.h
  ${PROJECT_SOURCE_DIR}/src/integrals/OneElectronIntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/OneElectronIntegralDerivativeCalculator.h
  ${PROJECT_SOURCE_DIR}/src/integrals/OneIntControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/integrals/RIIntegralDerivativeCalculator.h
  ${PROJECT_SOURCE_DIR}/src/integrals/RI_J_IntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/RI_J_IntegralControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/CholeskyDecomposer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/SimpleCholeskyDecomposer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/TwoElecFourCenterIntDecomposer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/TwoElecTwoCenterIntDecomposer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/ABTwoElecThreeCenterIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/CoulombInteractionIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/ExchangeInteractionIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/TwoElecFourCenterIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/TwoElecThreeCenterCalculator.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/TwoElecThreeCenterIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoExchangeIntegralTransformer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoHalfTransformer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoTransformer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libecpint.h
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint.h
  ${PROJECT_SOURCE_DIR}/src/io/CubeFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/DataOnGridWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/Eigen3HDF5.h
  ${PROJECT_SOURCE_DIR}/src/io/ExternalChargeReader.h
  ${PROJECT_SOURCE_DIR}/src/io/FCIDumpFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/Filesystem.h
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutput.h
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutputStream.h
  ${PROJECT_SOURCE_DIR}/src/io/GeneralGridFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/HDF5.h
  ${PROJECT_SOURCE_DIR}/src/io/IOOptions.h
  ${PROJECT_SOURCE_DIR}/src/io/MolecularSurfaceGridFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/PlaneFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/math/Derivatives.h
  ${PROJECT_SOURCE_DIR}/src/math/FloatMaths.h
  ${PROJECT_SOURCE_DIR}/src/math/IntegerMaths.h
  ${PROJECT_SOURCE_DIR}/src/math/LaplaceMinimaxWrapper.h
  ${PROJECT_SOURCE_DIR}/src/math/Matrix.h
  ${PROJECT_SOURCE_DIR}/src/math/RankFourTensor.h
  ${PROJECT_SOURCE_DIR}/src/math/RegularRankFourTensor.h
  ${PROJECT_SOURCE_DIR}/src/math/diis/ADIIS.h
  ${PROJECT_SOURCE_DIR}/src/math/diis/DIIS.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/JacobiRotation.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/MatrixFunctions.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/Orthogonalization.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/PadeApproximation.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/BFGS.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/LBFGS.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/NewtonRaphson.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/Optimizer.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SQNM.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SteepestDescent.h
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/Bofill.h
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/QST.h
  ${PROJECT_SOURCE_DIR}/src/memory/MemoryManager.h
  ${PROJECT_SOURCE_DIR}/src/misc/BasisSetTruncationAlgorithms.h
  ${PROJECT_SOURCE_DIR}/src/misc/FaTConvergenceAccelerator.h
  ${PROJECT_SOURCE_DIR}/src/misc/HelperFunctions.h
  ${PROJECT_SOURCE_DIR}/src/misc/RememberingFactory.h
  ${PROJECT_SOURCE_DIR}/src/misc/SerenityError.h
  ${PROJECT_SOURCE_DIR}/src/misc/SystemSplittingTools.h
  ${PROJECT_SOURCE_DIR}/src/misc/Timing.h
  ${PROJECT_SOURCE_DIR}/src/misc/VectorOnDiskStorageController.h
  ${PROJECT_SOURCE_DIR}/src/misc/VirtualOrbitalSelectionAlgorithms.h
  ${PROJECT_SOURCE_DIR}/src/misc/WarningTracker.h
  ${PROJECT_SOURCE_DIR}/src/notification/NotifyingClass.h
  ${PROJECT_SOURCE_DIR}/src/notification/ObjectSensitiveClass.h
  ${PROJECT_SOURCE_DIR}/src/parameters/AtomicParameters.h
  ${PROJECT_SOURCE_DIR}/src/parameters/Constants.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD_T.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_T0.h
  ${PROJECT_SOURCE_DIR}/src/postHF/ET/FDEDiabController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/ET/FDEETCalculator.h
  ${PROJECT_SOURCE_DIR}/src/postHF/ET/FDEETController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DeltaSpinSquared.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DipoleIntegrals.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ExcitationSpectrum.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFAnalysis.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFPopulationAnalysis.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/NROCalculator.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/NTOCalculator.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ResponseProperties.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Kernel/Kernel.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/LRSCFController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/ADC2Controller.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2Controller.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/RICC2/CC2HelperFunctions.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/CoulombSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/EOSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/ExchangeSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/FockSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/GrimmeSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/HyperkernelSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/KernelSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/RI/MRICoulombSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/RI/RICoulombSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/RI/RIExchangeSigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/Sigmavector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/Besley.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/CouplingConstruction.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/EigenvalueSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/IterativeSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/LRSCFRestart.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/LRSCFSetup.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/NonlinearEigenvalueSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/NonlinearResponseSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/RIIntegrals.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseLambda.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/SigmaCalculator.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/SimplifiedTDDFT.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/CouplingOrbitalSet.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/DomainOverlapMatrixController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/KLOrbitalSet.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalAOSigmaVectorWrapper.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalCorrelationController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/OrbitalPairDIISWrapper.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/GW_Analytic.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/GW_AnalyticContinuation.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/GW_ContourDeformation.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MBPT/MBPT.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/DipoleApproximationToPairEnergies.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LTMP2.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2InteractionCalculator.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/MP2.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/OrbitalPairSelector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/RIMP2.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundle.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundleFactory.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoreHamiltonian.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoulombInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABERIPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABEffectiveCorePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABFuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABLRExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABNAddFuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABZeroPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/BUReconstructionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/CDHFPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ChargeElectronInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ECPInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ERIPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/EffectiveCorePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangeInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/FuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HCorePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HFPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HoffmannProjectionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HuzinagaProjectionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/IncrementalFockMatrix.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LRXPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftHybridPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LoewdinFDEProjectionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/NAddFuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/NEInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/OptEffPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/PCMPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/Potential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/RICoulombPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/RIExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/SAOPPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/TDReconstructionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ZeroPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/ALMOPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/DFTPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/EDAPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/ESIPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentialBundleFactory.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/HFPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/PBEPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/PotentialBundle.h
  ${PROJECT_SOURCE_DIR}/src/scf/ConvergenceController.h
  ${PROJECT_SOURCE_DIR}/src/scf/DeltaScf.h
  ${PROJECT_SOURCE_DIR}/src/scf/ROHF.h
  ${PROJECT_SOURCE_DIR}/src/scf/SCFAnalysis.h
  ${PROJECT_SOURCE_DIR}/src/scf/Scf.h
  ${PROJECT_SOURCE_DIR}/src/scf/damper/Damper.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/AtomicDensityGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/DensityInitialGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/ExtendedHueckel.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/HCoreGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessFactory.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/SuperpositionOfAtomicPotentials.h
  ${PROJECT_SOURCE_DIR}/src/settings/BasisOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/CorrelatedMethodsOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/DFTOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/ElectronicStructureOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingSettings.h
  ${PROJECT_SOURCE_DIR}/src/settings/GeometryOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/GridOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/LRSCFOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/LocalizationOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/MBPTOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/MiscOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/Options.h
  ${PROJECT_SOURCE_DIR}/src/settings/OrthogonalizationOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/PCMOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/PCMSettings.h
  ${PROJECT_SOURCE_DIR}/src/settings/Reflection.h
  ${PROJECT_SOURCE_DIR}/src/settings/SCFOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/Settings.h
  ${PROJECT_SOURCE_DIR}/src/solvation/ContinuumModel.h
  ${PROJECT_SOURCE_DIR}/src/solvation/Solvents.h
  ${PROJECT_SOURCE_DIR}/src/system/System.h
  ${PROJECT_SOURCE_DIR}/src/system/SystemController.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ActiveSpaceSelectionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/BasisSetTruncationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/BrokenSymmetryTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/DFTEmbeddedLocalCorrelationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/DOSCCTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/DummyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/EDATask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronTransferTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronicStructureCopyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/EvaluateEnergyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportCavityTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportGridTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FCIDumpFileWriterTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FXDTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FiniteFieldTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/GWTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/GeneralizedDOSTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/HessianTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ImportCavityTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalCorrelationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task.h
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/OrbitalsIOTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/OrthogonalizationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/PCMInteractionEnergyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/PopAnalysisTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/QuasiRestrictedOrbitalsTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/TSTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/Task.h
  ${PROJECT_SOURCE_DIR}/src/tasks/TopDownStaticEmbeddingTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/VirtualOrbitalSpaceSelectionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/WavefunctionEmbeddingTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/WriteIntegralsTask.h
)

set(SERENITY_PYTHON_FILES
  ${PROJECT_SOURCE_DIR}/src/basis/BasisController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/data/ElectronicStructure_python.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals_python.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals_python.cpp
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyContributions_python.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry_python.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GridController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/Looper_python.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint_python.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/Timing_python.cpp
  ${PROJECT_SOURCE_DIR}/src/python/serenipy.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingSettings_python.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Options_python.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Settings_python.cpp
  ${PROJECT_SOURCE_DIR}/src/system/SystemController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronTransferTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportCavityTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FXDTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GWTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeneralizedDOSTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ImportCavityTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/OrbitalsIOTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/Task_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/VirtualOrbitalSpaceSelectionTask_python.cpp
)

set(SERENITY_TEST_FILES
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/BoughtonPulayAlgorithm_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/DOIBasedSelector_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PNOConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/TNOConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/brokenSymmetry/BrokenSymmetry_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/brokenSymmetry/CorrespondingOrbitals_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/ELFCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/SEDD_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/MultipoleMomentCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/NumericalDipoleMomentCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/EdmistonRuedenbergLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/FosterBoysLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/IBOLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/NonOrthogonalLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/OrbitalAligner_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/PipekMezeyLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/BeckePopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/CHELPGPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/CM5PopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/HirshfeldPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/IAOPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/MullikenPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisExtension_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CartesianToSphericalTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/SphericalHarmonicsRotations_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/ExternalChargeController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPair_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTriple_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/SpinPolarizedData_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombPotentialOnGridCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityAdder_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityMatrixDensityOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGrid_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DifferentialOverlapIntegralCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ElectrostaticPotentialOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ExternalDensityOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridData_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/MOCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ScalarOperatorToMatrixAdder_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/SupersystemDensityOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/CoefficientMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/FockMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/MatrixInBasis_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionCorrectionCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/LibXC_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/XCFun_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomTypeFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomType_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/DelleySurfaceConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Ellipse_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GEPOLSurfaceConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Line_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Plane_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Point_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Sphere_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Triangle_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/efields/ElectricFields_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/CoreCoreRepulsionDerivative_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/TDDFTGradientCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GaussLegendre_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/HilbertRTreeSorting_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGridFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/GridFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/sphere_lebedev_rule_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/CDIntegralController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/CDStorageController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/MO3CenterIntegralController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/decomposer/SimpleCholeskyDecomposer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoExchangeIntegralTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoHalfTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint_test.cpp
  ${PROJECT_SOURCE_DIR}/src/io/Eigen3HDF5_test.cpp
  ${PROJECT_SOURCE_DIR}/src/io/FCIDumpFileWriter_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/Derivatives_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/FloatMaths_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/IntegerMaths_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/Matrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/RankFourTensor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/RegularRankFourTensor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/JacobiRotation_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/MatrixFunctions_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/PadeApproximation_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/BFGS_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/NewtonRaphson_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SQNM_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SteepestDescent_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/Bofill_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/QST_test.cpp
  ${PROJECT_SOURCE_DIR}/src/memory/MemoryManager_test.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/RememberingFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/SerenityError_test.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/VectorOnDiskStorageController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CC_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_T0_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DeltaSpinSquared_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFPopulationAnalysis_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/NROCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/NTOCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Kernel/Kernel_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Sigmavectors/Sigmavector_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/Besley_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/EigenvalueSolver_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseSolver_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/DomainOverlapMatrixController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/DipoleApproximationToPairEnergies_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LTMP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2InteractionCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/MP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/OrbitalPairSelector_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/RIMP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoreHamiltonian_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoulombInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABERIPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABExchangePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABFuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABLRExchangePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABNAddFuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABZeroPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/BUReconstructionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ECPInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ERIPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/EffectiveCorePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangeInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/FuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HCorePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HoffmannProjectionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HuzinagaProjectionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LRXPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LoewdinFDEProjectionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NAddFuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NEInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/OptEffPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/PCMPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/RICoulombPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/SAOPPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ZeroPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/EDAPotentials_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/Scf_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/damper/Damper_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/AtomicDensityGuessCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/ExtendedHueckel_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/HCoreGuessCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/SuperpositionOfAtomicPotentials_test.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Settings_test.cpp
  ${PROJECT_SOURCE_DIR}/src/solvation/Solvents_test.cpp
  ${PROJECT_SOURCE_DIR}/src/system/SystemController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ActiveSpaceSelectionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/BasisSetTruncationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/BrokenSymmetryTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DOSCCTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EDATask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronTransferTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronicStructureCopyTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EvaluateEnergyTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportCavityTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportGridTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FXDTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FiniteFieldTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GWTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeneralizedDOSTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/HessianTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ImportCavityTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTaskBSE_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTaskCC2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTaskRI_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTaskSubTDDFT_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTaskTDDFT_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalCorrelationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/OrbitalsIOTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/OrthogonalizationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PCMInteractionEnergyTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PopAnalysisTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/QuasiRestrictedOrbitalsTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TSTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TopDownStaticEmbeddingTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/VirtualOrbitalSpaceSelectionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/WavefunctionEmbeddingTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/WriteIntegralsTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/BasisController__TEST_SUPPLY.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/BasisController__TEST_SUPPLY.h
  ${PROJECT_SOURCE_DIR}/src/testsupply/GridController__TEST_SUPPLY.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/GridController__TEST_SUPPLY.h
  ${PROJECT_SOURCE_DIR}/src/testsupply/SystemController__TEST_SUPPLY.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/SystemController__TEST_SUPPLY.h
)

