set(SERENITY_CPPS
  ${PROJECT_SOURCE_DIR}/src/system/SystemController.cpp
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentController.cpp
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentPrinter.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/SphericalHarmonicsRotations.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionProvider.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CartesianToSphericalTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionMapper.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/Transformation.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CustomBasisController.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisController.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisControllerFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/Shell.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisExtension.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisController.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/Functional.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/FunctionalLibrary.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/LibXC.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/XCFun.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionData.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionCorrectionCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/SCFAnalysis.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/ConvergenceController.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/Scf.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/DensityInitialGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/HCoreGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/AtomicDensityGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/SuperpositionOfAtomicPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/ExtendedHueckel.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/damper/DynamicDamping.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/damper/StaticDamping.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/damper/ArithmeticSeriesDamping.cpp
  ${PROJECT_SOURCE_DIR}/src/io/CubeFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/IOOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutput.cpp
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutputStream.cpp
  ${PROJECT_SOURCE_DIR}/src/io/DataOnGridWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/PlaneFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/GeneralGridFileWriter.cpp
  ${PROJECT_SOURCE_DIR}/src/io/Filesystem.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/BUReconstructionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/PCMPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/FuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HCorePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/IncrementalFockMatrix.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HuzinagaFDEProjectionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ECPInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NAddFuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HFPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/SAOPPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LRXPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangeInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ERIPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftHybridPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/OptEffPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NEInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/EffectiveCorePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/TDReconstructionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HoffmannProjectionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABERIPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABFuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABLRExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABExchangePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABEffectiveCorePotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoulombInteractionPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABNAddFuncPotential.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoreHamiltonian.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundleFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundle.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/PBEPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentialBundleFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/ESIPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/EDAPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/HFPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/DFTPotentials.cpp
  ${PROJECT_SOURCE_DIR}/src/memory/MemoryManager.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/DOIBasedSelecter.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PNOConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/TNOConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/BoughtonPulayAlgorithm.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/NumericalDipoleMomentCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/MultipoleMomentCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/EdmistonRuedenbergLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/IBOLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/OrbitalAligner.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/NonOrthogonalLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/SPADEAlgorithm.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/FosterBoysLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/PipekMezeyLocalization.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/ELFCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/SEDD.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/HirshfeldPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/IAOPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/MullikenPopulationCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/WarningTracker.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/FaTConvergenceAccelerator.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/SystemSplittingTools.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/Timing.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/VectorOnDiskStorageController.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/BasisSetTruncationAlgorithms.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/OneElectronIntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/MO3CenterIntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/RI_J_IntegralController.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libecpint.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoHalfTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoExchangeIntegralTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/SCFOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/ElectronicStructureOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/LRSCFOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/PCMOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/LocalizationOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/CorrelatedMethodsOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/GeometryOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/GridOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Settings.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/BasisOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/DFTOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/MiscOptions.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GridController.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/HilbertRTreeSorting.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GridControllerFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGridFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/GridFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/sphere_lebedev_rule.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/RIMP2.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/DipoleApproximationToPairEnergies.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/MP2.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/OrbitalPairSelector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/LRSCFController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Kernel/Kernel.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ExcitationSpectrum.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ResponseProperties.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFAnalysis.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DipoleIntegrals.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/DeltaESigmaVector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/KernelSigmaVector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/SigmaVector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/CoulombSigmaVector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/EOSigmaVector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/KSigmaVector.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseSolver.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/Besley.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/EigenvalueSolver.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/LRSCFSetup.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD_T.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_T0.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/CouplingOrbitalSet.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalAOSigmaVectorWrapper.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/DomainOverlapMatrixController.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/KLOrbitalSet.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/OrbitalPairDIISWrapper.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalCorrelationController.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronicStructureCopyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/HessianTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportGridTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DummyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EDATask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ActiveSpaceSelectionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EvaluateEnergyTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/BasisSetTruncationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PopAnalysisTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TSTask.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask.cpp
  ${PROJECT_SOURCE_DIR}/src/data/SparseMapsController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTriple.cpp
  ${PROJECT_SOURCE_DIR}/src/data/PAOController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/ElectronicStructure.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPair.cpp
  ${PROJECT_SOURCE_DIR}/src/data/SingleSubstitution.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ExternalDensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DifferentialOverlapIntegralCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/MOCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/SupersystemDensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityMatrixDensityOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ElectrostaticPotentialOnGridController.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/MatrixOperatorToGridTransformer.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridControllerFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombPotentialOnGridCalculator.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityAdder.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ScalarOperatorToMatrixAdder.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Plane.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomTypeFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Triangle.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Ellipse.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Point.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Sphere.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceController.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Line.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryFileReader.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Atom.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceFactory.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/XyzFileToGeometryConverter.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/DelleySurfaceConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GEPOLSurfaceConstructor.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomType.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalHessianCalc.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalGeomGradCalc.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/CoreCoreRepulsionDerivative.cpp
  ${PROJECT_SOURCE_DIR}/src/solvation/Solvents.cpp
  ${PROJECT_SOURCE_DIR}/src/solvation/ContinuumModel.cpp
  ${PROJECT_SOURCE_DIR}/src/math/ScalarProductMatrix.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/LBFGS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/BFGS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SteepestDescent.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/NewtonRaphson.cpp
  ${PROJECT_SOURCE_DIR}/src/math/diis/DIIS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/diis/ADIIS.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/DirectCD.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/JacobiRotation.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/CholeskyDecomposer.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/QST.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/Bofill.cpp
)

set(SERENITY_HEADERS
  ${PROJECT_SOURCE_DIR}/src/system/SystemController.h
  ${PROJECT_SOURCE_DIR}/src/system/System.h
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentController.h
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyContributions.h
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyComponentPrinter.h
  ${PROJECT_SOURCE_DIR}/src/basis/SphericalHarmonicsRotations.h
  ${PROJECT_SOURCE_DIR}/src/basis/CartesianToSphericalTransformer.h
  ${PROJECT_SOURCE_DIR}/src/basis/Basis.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisExtension.h
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/basis/Shell.h
  ${PROJECT_SOURCE_DIR}/src/basis/ABShellPairCalculator.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionMapper.h
  ${PROJECT_SOURCE_DIR}/src/basis/Transformation.h
  ${PROJECT_SOURCE_DIR}/src/basis/AtomCenteredBasisController.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisController.h
  ${PROJECT_SOURCE_DIR}/src/basis/CustomBasisController.h
  ${PROJECT_SOURCE_DIR}/src/basis/BasisFunctionProvider.h
  ${PROJECT_SOURCE_DIR}/src/dft/Functional.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/FunctionalLibrary.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/LibXC.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/XCFun.h
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/PartialDerivatives.h
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionCorrectionCalculator.h
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionData.h
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionRawData.h
  ${PROJECT_SOURCE_DIR}/src/scf/Scf.h
  ${PROJECT_SOURCE_DIR}/src/scf/ConvergenceController.h
  ${PROJECT_SOURCE_DIR}/src/scf/SCFAnalysis.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessFactory.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/DensityInitialGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/HCoreGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/SuperpositionOfAtomicPotentials.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/AtomicDensityGuessCalculator.h
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/ExtendedHueckel.h
  ${PROJECT_SOURCE_DIR}/src/scf/damper/ArithmeticSeriesDamping.h
  ${PROJECT_SOURCE_DIR}/src/scf/damper/DynamicDamping.h
  ${PROJECT_SOURCE_DIR}/src/scf/damper/StaticDamping.h
  ${PROJECT_SOURCE_DIR}/src/scf/damper/Damper.h
  ${PROJECT_SOURCE_DIR}/src/io/HDF5.h
  ${PROJECT_SOURCE_DIR}/src/io/Filesystem.h
  ${PROJECT_SOURCE_DIR}/src/io/DataOnGridWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/Eigen3HDF5.h
  ${PROJECT_SOURCE_DIR}/src/io/CubeFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutputStream.h
  ${PROJECT_SOURCE_DIR}/src/io/IOOptions.h
  ${PROJECT_SOURCE_DIR}/src/io/GeneralGridFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/PlaneFileWriter.h
  ${PROJECT_SOURCE_DIR}/src/io/FormattedOutput.h
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/TDReconstructionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangeInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HCorePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/Potential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LRXPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HFPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/NAddFuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/LevelshiftHybridPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/BUReconstructionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/SAOPPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/NEInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ERIPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/PCMPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/EffectiveCorePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/FuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ECPInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HoffmannProjectionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ZeroPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/IncrementalFockMatrix.h
  ${PROJECT_SOURCE_DIR}/src/potentials/OptEffPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/HuzinagaFDEProjectionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABNAddFuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABLRExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoulombInteractionPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABZeroPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABExchangePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABERIPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABEffectiveCorePotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABFuncPotential.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoreHamiltonian.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundle.h
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABBundles/ABEmbeddedBundleFactory.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/HFPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/ESIPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentialBundleFactory.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/EDAPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/PotentialBundle.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/DFTPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/PBEPotentials.h
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/FDEPotentials.h
  ${PROJECT_SOURCE_DIR}/src/memory/MemoryManager.h
  ${PROJECT_SOURCE_DIR}/src/memory/AvailableMemory.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/DOIBasedSelecter.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PNOConstructor.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PAOSelecter.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/TNOConstructor.h
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/BoughtonPulayAlgorithm.h
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/NumericalDipoleMomentCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/MultipoleMomentCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/Localization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/NonOrthogonalLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/PipekMezeyLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/SPADEAlgorithm.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/IBOLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/FosterBoysLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/OrbitalAligner.h
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/EdmistonRuedenbergLocalization.h
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/ELFCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/SEDD.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/HirshfeldPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/MullikenPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/IAOPopulationCalculator.h
  ${PROJECT_SOURCE_DIR}/src/misc/BasisSetTruncationAlgorithms.h
  ${PROJECT_SOURCE_DIR}/src/misc/SystemSplittingTools.h
  ${PROJECT_SOURCE_DIR}/src/misc/Timing.h
  ${PROJECT_SOURCE_DIR}/src/misc/HelperFunctions.h
  ${PROJECT_SOURCE_DIR}/src/misc/FaTConvergenceAccelerator.h
  ${PROJECT_SOURCE_DIR}/src/misc/VectorOnDiskStorageController.h
  ${PROJECT_SOURCE_DIR}/src/misc/SerenityError.h
  ${PROJECT_SOURCE_DIR}/src/misc/WarningTracker.h
  ${PROJECT_SOURCE_DIR}/src/misc/RememberingFactory.h
  ${PROJECT_SOURCE_DIR}/src/input/Input.h
  ${PROJECT_SOURCE_DIR}/src/integrals/OneIntControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/integrals/OneElectronIntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/MO3CenterIntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/RI_J_IntegralController.h
  ${PROJECT_SOURCE_DIR}/src/integrals/RI_J_IntegralControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/integrals/Normalization.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/CoulombInteractionIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/ExchangeInteractionIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/ABTwoElecThreeCenterIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/TwoElecFourCenterIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/TwoElecThreeCenterIntLooper.h
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint.h
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libecpint.h
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoHalfTransformer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoExchangeIntegralTransformer.h
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoTransformer.h
  ${PROJECT_SOURCE_DIR}/src/settings/LocalizationOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/PCMSettings.h
  ${PROJECT_SOURCE_DIR}/src/settings/Settings.h
  ${PROJECT_SOURCE_DIR}/src/settings/MiscOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/BasisOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/Reflection.h
  ${PROJECT_SOURCE_DIR}/src/settings/CorrelatedMethodsOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingSettings.h
  ${PROJECT_SOURCE_DIR}/src/settings/LRSCFOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/GridOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/ElectronicStructureOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/SCFOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/Options.h
  ${PROJECT_SOURCE_DIR}/src/settings/PCMOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/DFTOptions.h
  ${PROJECT_SOURCE_DIR}/src/settings/GeometryOptions.h
  ${PROJECT_SOURCE_DIR}/src/grid/GridControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/grid/Grid.h
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGrid.h
  ${PROJECT_SOURCE_DIR}/src/grid/GridController.h
  ${PROJECT_SOURCE_DIR}/src/grid/HilbertRTreeSorting.h
  ${PROJECT_SOURCE_DIR}/src/grid/AtomCenteredGridController.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/GridFactory.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGrid.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGridFactory.h
  ${PROJECT_SOURCE_DIR}/src/grid/construction/sphere_lebedev_rule.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/RIMP2.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/MP2.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/OrbitalPairSelector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/DipoleApproximationToPairEnergies.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/LRSCFController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Kernel/Kernel.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/LRSCFAnalysis.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ResponseProperties.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/ExcitationSpectrum.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Analysis/DipoleIntegrals.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/KSigmaVector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/DeltaESigmaVector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/KernelSigmaVector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/EOSigmaVector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/CoulombSigmaVector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/SigmaVector.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/Besley.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/LRSCFSetup.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/IterativeSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/EigenvalueSolver.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD_T.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_T0.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD.h
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CCSD.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/KLOrbitalSet.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/OrbitalPairDIISWrapper.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalCorrelationController.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/CouplingOrbitalSet.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/LocalAOSigmaVectorWrapper.h
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/DomainOverlapMatrixController.h
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/BasisSetTruncationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronicStructureCopyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task.h
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/EDATask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/Task.h
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/TSTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/EvaluateEnergyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ActiveSpaceSelectionTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/PopAnalysisTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/HessianTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/DummyTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportGridTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask.h
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPair.h
  ${PROJECT_SOURCE_DIR}/src/data/ElectronicStructure.h
  ${PROJECT_SOURCE_DIR}/src/data/SparseMapsController.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalController.h
  ${PROJECT_SOURCE_DIR}/src/data/PAOController.h
  ${PROJECT_SOURCE_DIR}/src/data/SingleSubstitution.h
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTriple.h
  ${PROJECT_SOURCE_DIR}/src/data/SpinPolarizedData.h
  ${PROJECT_SOURCE_DIR}/src/data/DoublySpinPolarizedData.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/SPMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/MatrixInBasis.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/CoefficientMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController.h
  ${PROJECT_SOURCE_DIR}/src/data/matrices/FockMatrix.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/MOCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/ExternalDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridPotential.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityMatrixDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityAdder.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/ScalarOperatorToMatrixAdder.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/SupersystemDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridControllerFactory.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGrid.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombPotentialOnGridCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridData.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/ElectrostaticPotentialOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/MatrixOperatorToGridTransformer.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridFactory.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/DifferentialOverlapIntegralCalculator.h
  ${PROJECT_SOURCE_DIR}/src/data/grid/CustomDensityOnGridController.h
  ${PROJECT_SOURCE_DIR}/src/geometry/XyzFileToGeometryConverter.h
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceController.h
  ${PROJECT_SOURCE_DIR}/src/geometry/DelleySurfaceConstructor.h
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryFactory.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry.h
  ${PROJECT_SOURCE_DIR}/src/geometry/GeometryFileReader.h
  ${PROJECT_SOURCE_DIR}/src/geometry/MolecularSurfaceFactory.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Line.h
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomType.h
  ${PROJECT_SOURCE_DIR}/src/geometry/GEPOLSurfaceConstructor.h
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomTypeFactory.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Plane.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Triangle.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Atom.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Sphere.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Point.h
  ${PROJECT_SOURCE_DIR}/src/geometry/Ellipse.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalHessianCalc.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/GeometryGradientCalculator.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/NumericalGeomGradCalc.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/HessianCalculator.h
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/CoreCoreRepulsionDerivative.h
  ${PROJECT_SOURCE_DIR}/src/solvation/ContinuumModel.h
  ${PROJECT_SOURCE_DIR}/src/solvation/Solvents.h
  ${PROJECT_SOURCE_DIR}/src/notification/NotifyingClass.h
  ${PROJECT_SOURCE_DIR}/src/notification/ObjectSensitiveClass.h
  ${PROJECT_SOURCE_DIR}/src/math/RegularRankFourTensor.h
  ${PROJECT_SOURCE_DIR}/src/math/ScalarProductMatrix.h
  ${PROJECT_SOURCE_DIR}/src/math/Matrix.h
  ${PROJECT_SOURCE_DIR}/src/math/FloatMaths.h
  ${PROJECT_SOURCE_DIR}/src/math/RankFourTensor.h
  ${PROJECT_SOURCE_DIR}/src/math/VectorMaths.h
  ${PROJECT_SOURCE_DIR}/src/math/Derivatives.h
  ${PROJECT_SOURCE_DIR}/src/math/IntegerMaths.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SteepestDescent.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/NewtonRaphson.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/LBFGS.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/Optimizer.h
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/BFGS.h
  ${PROJECT_SOURCE_DIR}/src/math/diis/ADIIS.h
  ${PROJECT_SOURCE_DIR}/src/math/diis/DIIS.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/MatrixFunctions.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/Orthogonalization.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/JacobiRotation.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/DirectCD.h
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/CholeskyDecomposer.h
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/Bofill.h
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/QST.h
  ${PROJECT_SOURCE_DIR}/src/parameters/Constants.h
  ${PROJECT_SOURCE_DIR}/src/parameters/AtomicParameters.h
)

set(SERENITY_PYTHON_FILES
  ${PROJECT_SOURCE_DIR}/src/system/SystemController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/energies/EnergyContributions_python.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals_python.cpp
  ${PROJECT_SOURCE_DIR}/src/python/serenipy.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/Timing_python.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/looper/Looper_python.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint_python.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Options_python.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/EmbeddingSettings_python.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Settings_python.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/GridController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/Task_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LocalizationTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask_python.cpp
  ${PROJECT_SOURCE_DIR}/src/data/ElectronicStructure_python.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController_python.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry_python.cpp
)

set(SERENITY_TEST_FILES
  ${PROJECT_SOURCE_DIR}/src/system/SystemController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/Shell_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/SphericalHarmonicsRotations_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/CartesianToSphericalTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/basis/BasisExtension_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/CompositeFunctionals_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/BasicFunctionals_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/XCFun_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/functionals/wrappers/LibXC_test.cpp
  ${PROJECT_SOURCE_DIR}/src/dft/dispersionCorrection/DispersionCorrectionCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/Scf_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/HCoreGuessCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/AtomicDensityGuessCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/ExtendedHueckel_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/InitialGuessCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/initialGuess/SuperpositionOfAtomicPotentials_test.cpp
  ${PROJECT_SOURCE_DIR}/src/scf/damper/StaticDamping_test.cpp
  ${PROJECT_SOURCE_DIR}/src/io/Eigen3HDF5_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/PCMPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/BUReconstructionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ECPInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NAddFuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HCorePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HoffmannProjectionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/EffectiveCorePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/OptEffPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/CoulombPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/HuzinagaFDEProjectionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangeInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/LRXPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/NEInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ExchangePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ERIPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/SAOPPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ZeroPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/FuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABFuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABExchangePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABNAddFuncPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoulombInteractionPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABCoreHamiltonian_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABZeroPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABLRExchangePotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/ABFockMatrixConstruction/ABERIPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/potentials/bundles/EDAPotentials_test.cpp
  ${PROJECT_SOURCE_DIR}/src/memory/MemoryManager_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/BoughtonPulayAlgorithm_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/DOIBasedSelecter_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/TNOConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/QuasiCanonicalPAODomainConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/PAOSelection/PNOConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/MultipoleMomentCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/multipoles/NumericalDipoleMomentCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/OrbitalAligner_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/PipekMezeyLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/FosterBoysLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/EdmistonRuedenbergLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/NonOrthogonalLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/orbitalLocalization/IBOLocalization_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/SEDD_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/localizationFunctions/ELFCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/MullikenPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/IAOPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/analysis/populationAnalysis/HirshfeldPopulationCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/VectorOnDiskStorageController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/RememberingFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/misc/SerenityError_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/MO3CenterIntegralController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/wrappers/Libint_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoExchangeIntegralTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoHalfTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/integrals/transformer/Ao2MoTransformer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/settings/Settings_test.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/GridController__TEST_SUPPLY.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/GridController__TEST_SUPPLY.h
  ${PROJECT_SOURCE_DIR}/src/testsupply/BasisController__TEST_SUPPLY.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/SystemController__TEST_SUPPLY.h
  ${PROJECT_SOURCE_DIR}/src/testsupply/SystemController__TEST_SUPPLY.cpp
  ${PROJECT_SOURCE_DIR}/src/testsupply/BasisController__TEST_SUPPLY.h
  ${PROJECT_SOURCE_DIR}/src/grid/HilbertRTreeSorting_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/sphere_lebedev_rule_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/AtomGridFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/grid/construction/GridFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/DipoleApproximationToPairEnergies_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/LocalMP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/MP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/RIMP2_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/MPn/OrbitalPairSelector_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/LRSCFController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Kernel/Kernel_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/SigmaVectors/SigmaVector_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/Besley_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/ResponseSolver_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LRSCF/Tools/EigenvalueSolver_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/CC_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/CC/DLPNO_CCSD_T0_test.cpp
  ${PROJECT_SOURCE_DIR}/src/postHF/LocalCorrelation/DomainOverlapMatrixController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TSTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MultipoleMomentTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/MP2Task_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/BasisSetTruncationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/HessianTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ElectronicStructureCopyTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FDETask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EvaluateEnergyTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/LRSCFTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/FreezeAndThawTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemSplittingTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/TDEmbeddingTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GradientTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ActiveSpaceSelectionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/DispersionCorrectionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ScfTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/CoupledClusterTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/SystemAdditionTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PopAnalysisTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/PlotTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/EDATask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/GeometryOptimizationTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/tasks/ExportGridTask_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalTriple_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalPair_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/OrbitalController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/SpinPolarizedData_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/CoefficientMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/MatrixInBasis_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/DensityMatrixController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/matrices/FockMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGrid_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/BasisFunctionOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityAdder_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DifferentialOverlapIntegralCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ScalarOperatorToMatrixAdder_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/MOCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/SupersystemDensityOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/CoulombPotentialOnGridCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ExternalDensityOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/ElectrostaticPotentialOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridPotential_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityOnGridCalculator_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/DensityMatrixDensityOnGridController_test.cpp
  ${PROJECT_SOURCE_DIR}/src/data/grid/GridData_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Sphere_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomType_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Line_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/GEPOLSurfaceConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/AtomTypeFactory_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Triangle_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/DelleySurfaceConstructor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Geometry_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Point_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Plane_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/Ellipse_test.cpp
  ${PROJECT_SOURCE_DIR}/src/geometry/gradients/CoreCoreRepulsionDerivative_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/IntegerMaths_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/RegularRankFourTensor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/Matrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/ScalarProductMatrix_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/RankFourTensor_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/Derivatives_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/FloatMaths_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/VectorMaths_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/SteepestDescent_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/BFGS_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/optimizer/NewtonRaphson_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/DirectCD_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/MatrixFunctions_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/JacobiRotation_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/linearAlgebra/CholeskyDecomposer_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/QST_test.cpp
  ${PROJECT_SOURCE_DIR}/src/math/saddlepoint/Bofill_test.cpp
)

